### ISSUE TITLE
Build Error: Could not resolve dependencies for project org.flowable:flowable-spring-boot-starter-rest-api:jar:6.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by Tarekajaj** [flowable/flowable-engine#955]
Hello,

We are trying to extend flowable-ui-modeler app with some functionality, we made the required changes and tried to rebuild the project by running `mvn -Pdistro clean install -DskipTests` at the root of the project but it fails at **flowable-spring-boot-starter-rest-api** with the following error:

`Failed to execute goal on project flowable-spring-boot-starter-rest-api: Could not resolve dependencies for project org.flowable:flowable-spring-boot-starter-rest-api:jar:6.3.0-SNAPSHOT: Could not find artifact org.flowable:flowable-spring-boot-starter-process:jar:6.3.0-SNAPSHOT in spring-snapshots (http://repo.spring.io/snapshot) -> [Help 1]`

Is this a bug? or are we doing it wrong?

Best Regards,

**Comment by tijsrademakers** [comment]
Hi,

This has been fixed on the current master. Also note that 6.3.0 has been released yesterday, so these artefacts are available in Maven central.

Best regards

**Comment by Tarekajaj** [comment]
Was coming here to report it is fixed in latest release, to found your comment. Many thanks.

**Comment by tijsrademakers** [comment]
Cool :-), thanks for checking

**Comment by n0mer** [comment]
@tijsrademakers do you publish snapshot builds ?

**Comment by tijsrademakers** [comment]
No, we don't publish snapshot builds

**Comment by sagaraa** [comment]
I am Still facing the error 
maven couldn't find flowable-http jar file 

any suggestions how to handle it?

**Comment by tijsrademakers** [comment]
https://search.maven.org/search?q=a:flowable-http
